= 关于groovyBoot
作者：肖鹏 <13910818313@163.com>
:v1.4.0.0.M1, 2023-11-25
:imagesdir: ./images
:source-highlighter: coderay
:last-update-label!:
:toc2:
:sectnums:


groovyBoot是一套提供快速开发的支持框架,希望通过增加对基本开发的规约要求，使开发人员聚焦于业务逻辑，避免在框架层耗费时间精力。
通过对springBoot的集成，提供对springMVC的优化，在使用GORM(groovy-ORM)统一对数据层的操作。在对spring security进行深度集成后，提供一整套的安全防护方案包括JWT,token,oauth2等。
为了加快业务系统的建设，缩短项目的开发周期,groovyBoot将提供在线的起步生成器:link:https://start.declare.org.cn/[groovyBoot起步器],
项目开源文件在link:https://github.com/groovyBoot/[groovyBoot框架]



TIP:框架1.4.0.0支持JDK11及以上;采用spring boot 2.7.18创建, spring的版本是5.3.31, spring security的版本都是5.8.8, hibernate的版本是5.6.15.Final, GORM采用全新的8.0.2版本.


////
框架1.3.1.0采用spring boot 2.7.3创建, spring的版本是5.3.20, spring security的版本都是5.6.5, hibernate的版本是5.6.14.Final, GORM采用全新的7.3.1版本.
//

//框架1.3.1.0采用spring boot 2.7.3创建, spring的版本是5.3.20, spring security的版本都是5.6.5, hibernate的版本是5.6.14.Final, GORM采用全新的7.3.1版本.
//框架1.1采用spring boot 2.2.8.RELEASE创建, spring的版本是5.2.7.RELEASE, spring security的版本都是5.2.6.RELEASE, hibernate的版本是5.4.10.Final, GORM采用全新的7.1.0.M2版本.




////
 TIP: 因为spring5.2，5.3版本中逐步弃用RequestMappingHandlerMapping方式，改用PathMatchConfigurer方式，需要在项目中自己去整理uri映射。
参看：https://github.com/spring-projects/spring-framework/issues/23915#issuecomment-563987147
参看：https://docs.spring.io/spring-framework/docs/5.2.x/spring-framework-reference/web.html#mvc-config-path-matching
//

== 建议

建议采用如下的技术平台构建项目

[format="csv", options="header"]
|===
分类,推荐,说明
开发工具,idea intellij,
构建工具,gradle,
代码管理,git,
开发语言,groovy + java,
制品类型,docker,
CI/CD,jenkins,
配置文件类型,*.yml,
|===

== 循序渐进

使用groovyBoot的路线参看如下：

[format="csv", options="header"]
|===
名称,描述,说明
link:./groovyBootGuide/introduce.html[入门介绍],简单介绍入门操作,
link:./groovyBootGuide/projectStructure.html[项目结构],从结构入手介绍使用initializr生成的项目情况,
link:./groovyBootGuide/security.html[安全部分],介绍springsecurity的安全封装,
link:./groovyBootGuide/language.html[语言区别],介绍groovy语言的特点,
link:./groovyBootGuide/agreement.html[开发规约],介绍groovyboot项目的开发规约（约定大于配置）,
link:./groovyBootGuide/dataOperator.html[数据操作],介绍GORM中的约束、映射及字节码增加的方法,
link:./groovyBootGuide/component.html[组件介绍],介绍groovyboot中可供选择使用的组件,
link:./groovyBootGuide/skill.html[开发经验],一些数据操作的经验分享,
link:./groovyBootGuide/event.html[事件机制],groovyboot体系的事件机制,
link:./groovyBootGuide/json.html[json操作],关于项目中的json操作,
|===

